-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력

-- 

WITH PLAN AS(
    SELECT P.PLAN_ID, P.CAR_TYPE, 
        CAST(SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS UNSIGNED) AS DURATION_LIMIT, 
        CAST(SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS UNSIGNED) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
)

SELECT 
    H.HISTORY_ID, 
    -- 대여 금액 계산
    ROUND( 
        (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100
        * C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
   ) AS FEE
    
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
     LEFT JOIN PLAN P ON C.CAR_TYPE = P.CAR_TYPE
        AND P.DURATION_LIMIT = (
            SELECT MAX(DURATION_LIMIT)
            FROM PLAN
            WHERE C.CAR_TYPE = CAR_TYPE
                AND DURATION_LIMIT <= DATEDIFF(H.END_DATE, H.START_DATE) + 1
        )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
