-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회

WITH ORDER_NUM AS(
    SELECT 
        J.FLAVOR, 
        SUM(J.TOTAL_ORDER) + SUM(IFNULL(H.TOTAL_ORDER, 0)) AS ORDERS
    FROM FIRST_HALF H RIGHT JOIN JULY J ON H.SHIPMENT_ID = J.SHIPMENT_ID
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM ORDER_NUM
GROUP BY FLAVOR
ORDER BY ORDERS DESC
LIMIT 3