SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
    # DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d %H:%i:%S.%f') AS APNT_YMD
FROM APPOINTMENT A 
    JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID 
    JOIN PATIENT P ON P.PT_NO = A.PT_NO
WHERE A.APNT_YMD LIKE '2022-04-13%' 
    AND A.MCDP_CD = 'CS' 
    AND APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC