-- 몇 시에 입양이 가장 활발하게 일어나는지

WITH RECURSIVE HOURS AS(
    SELECT 0 AS HOUR
    
    UNION
    
    SELECT (H.HOUR + 1) AS HOUR
    FROM HOURS H
    WHERE H.HOUR < 23
)

SELECT 
    H.HOUR, 
    COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A RIGHT JOIN HOURS H ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR -- 있는거 기준으로 그룹핑해야 함. 
ORDER BY HOUR ASC












# WITH RECURSIVE HOURS AS(
#     SELECT 0 AS HOUR
    
#     UNION
    
#     SELECT (H.HOUR + 1) AS HOUR 
#     FROM HOURS H
#     WHERE H.HOUR < 23
# )

# SELECT 
#     H.HOUR AS HOUR, 
#     IFNULL(COUNT(A.ANIMAL_ID), 0) AS COUNT
# FROM ANIMAL_OUTS A RIGHT JOIN HOURS H ON HOUR(A.DATETIME) = H.HOUR
# GROUP BY H.HOUR
# ORDER BY HOUR ASC