-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

WITH REVIEW_COUNT AS(
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
    FROM REST_REVIEW R
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_CNT DESC
    LIMIT 1
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM MEMBER_PROFILE M NATURAL JOIN REST_REVIEW R 
WHERE M.MEMBER_ID IN (
    SELECT C.MEMBER_ID
    FROM REVIEW_COUNT C
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC




# SELECT M.MEMBER_NAME, 
#     R.REVIEW_TEXT, 
#     DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE M NATURAL JOIN REST_REVIEW R
# NATURAL JOIN (
#     SELECT MEMBER_ID 
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID 
#     ORDER BY COUNT(*) DESC 
#     LIMIT 1
# ) TOP

# ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC


