-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름을 조회

-- 식품 분류별로의 가장 비싼 가격
# WITH EXP_PRICE AS(
#     SELECT CATEGORY, MAX(PRICE) AS EXP_PRICE
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY
# )


SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유') 
    AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = F.CATEGORY GROUP BY CATEGORY)
    
GROUP BY F.CATEGORY

ORDER BY PRICE DESC
